interface ErrorCodeMap {
    [code: number]: string;
}

// JSON.parse is used to avoid long javascript syntax and semantical parsing
export const errorCodes: ErrorCodeMap = JSON.parse(`{
    "1001": "missing or malformed jwt token",
    "1002": "invalid or expired jwt",
    "1003": "invalid email",
    "1004": "auth code not available",
    "1005": "invalid auth code or email",
    "1006": "auth code expired",
    "1007": "invalid refresh token",
    "1008": "expired refresh token",
    "1009": "invalid signature",
    "1010": "invalid signature or address",
    "2001": "too long payment description, max length 1024",
    "2002": "asset cannot be empty",
    "2003": "withdraw addresses must be filled or empty both",
    "2004": "asset amount too small",
    "2005": "payment doesnt exists",
    "2006": "payment id cannot be empty",
    "2007": "asset not found",
    "2008": "withdraw addresses cannot be empty, because default addresse not installed in merchant",
    "2009": "invalid payment blockchain",
    "2010": "payment not pending",
    "2011": "unsupported payment asset for tron",
    "2012": "specified blockchain already selected",
    "2013": "assets cannot be empty",
    "2014": "asset not available for accepting",
    "3001": "bad merchant name length",
    "3002": "bad merchant description length",
    "3003": "merchant with specified name already exists",
    "3004": "merchant with specified id doesn't exists",
    "3005": "merchant domain already verified",
    "3006": "merchant domain check not available",
    "3007": "merchant domain verification code not found",
    "3008": "merchant domain verification lookup unavailable",
    "3009": "...",
    "3010": "merchant with specified domain already exists",
    "3011": "x-merchant-id header cannot be empty",
    "3012": "x-signature header cannot be empty",
    "3013": "invalid x-merchant-id header",
    "3014": "merchant api unavailable",
    "3015": "unsupported domain verification method",
    "4001": "bad domain format",
    "4002": "invalid evm address",
    "4003": "invalid tron address",
    "4004": "invalid url",
    "4005": "nothing to update",
    "4006": "invalid withdraw address",
    "4007": "invalid authorization address",
    "4008": "value cannot be empty",
    "5001": "unsupported network",
    "5002": "merchants wallet already exists",
    "5003": "merchants wallet doesn't exists"
  }`);
